import type { CompetitorData, FunnelData, ProcedureData } from './types'

export const MOCK_COMPETITOR_DATA: Record<string, CompetitorData> = {
  default: {
    keyword: '보톡스',
    monthlySearchVol: 45200,
    relatedContentCnt: 1847,
    competitorAdCnt: 38,
    avgViewCount: 12400,
    relatedKeywords: [
      { keyword: '보톡스 가격', relevanceScore: 95, monthlySearchVol: 19800 },
      { keyword: '강남 보톡스', relevanceScore: 88, monthlySearchVol: 12300 },
      { keyword: '보톡스 효과', relevanceScore: 82, monthlySearchVol: 9100 },
      { keyword: '보톡스 부작용', relevanceScore: 74, monthlySearchVol: 6700 },
      { keyword: '보톡스 지속기간', relevanceScore: 65, monthlySearchVol: 4200 },
    ],
    topContents: [
      { rank: 1, title: '보톡스 시술 전후 비교 (강남 직접 체험)', hospitalName: '△△의원', platform: 'INSTAGRAM', viewCount: 284000 },
      { rank: 2, title: '보톡스 후기 인터뷰 | 솔직 리얼 후기', hospitalName: 'XX병원', platform: 'YOUTUBE', viewCount: 198000 },
      { rank: 3, title: '강남역 보톡스 가격 비교 총정리', hospitalName: '○○피부과', platform: 'NAVER_BLOG', viewCount: 142000 },
      { rank: 4, title: '보톡스 맞기 전 꼭 알아야 할 것들', hospitalName: '□□클리닉', platform: 'YOUTUBE', viewCount: 118000 },
      { rank: 5, title: '보톡스 vs 필러 차이점 완벽 정리', hospitalName: '☆☆성형외과', platform: 'NAVER_BLOG', viewCount: 97000 },
      { rank: 6, title: '보톡스 자연스럽게 맞는 법 | 원장이 알려주는 꿀팁', hospitalName: '◇◇피부과', platform: 'INSTAGRAM', viewCount: 83000 },
      { rank: 7, title: '이마 보톡스 3개월 후기', hospitalName: '▽▽의원', platform: 'YOUTUBE', viewCount: 71000 },
      { rank: 8, title: '보톡스 가격 낮추는 현명한 방법', hospitalName: '△△클리닉', platform: 'NAVER_BLOG', viewCount: 64000 },
      { rank: 9, title: '보톡스 시술 당일 주의사항', hospitalName: 'YY피부과', platform: 'INSTAGRAM', viewCount: 52000 },
      { rank: 10, title: '사각턱 보톡스 6개월 변화 기록', hospitalName: 'ZZ의원', platform: 'YOUTUBE', viewCount: 44000 },
    ],
    dataSource: 'mock',
  },
  울쎄라: {
    keyword: '울쎄라',
    monthlySearchVol: 38600,
    relatedContentCnt: 1203,
    competitorAdCnt: 29,
    avgViewCount: 18200,
    relatedKeywords: [
      { keyword: '울쎄라 가격', relevanceScore: 97, monthlySearchVol: 16400 },
      { keyword: '슈링크 vs 울쎄라', relevanceScore: 89, monthlySearchVol: 10200 },
      { keyword: '울쎄라 효과', relevanceScore: 83, monthlySearchVol: 7800 },
      { keyword: '울쎄라 부작용', relevanceScore: 71, monthlySearchVol: 5100 },
      { keyword: '울쎄라 강남', relevanceScore: 62, monthlySearchVol: 3900 },
    ],
    topContents: [
      { rank: 1, title: '울쎄라 300샷 시술 전후 비교', hospitalName: 'AA피부과', platform: 'YOUTUBE', viewCount: 312000 },
      { rank: 2, title: '울쎄라 vs 슈링크 솔직 비교 후기', hospitalName: 'BB클리닉', platform: 'NAVER_BLOG', viewCount: 224000 },
      { rank: 3, title: '울쎄라 1달 후기 (붓기 사진 포함)', hospitalName: 'CC의원', platform: 'INSTAGRAM', viewCount: 187000 },
      { rank: 4, title: '울쎄라 가격 협상 팁 공개', hospitalName: 'DD성형외과', platform: 'NAVER_BLOG', viewCount: 143000 },
      { rank: 5, title: '울쎄라 효과 없다? 진실은?', hospitalName: 'EE피부과', platform: 'YOUTUBE', viewCount: 121000 },
      { rank: 6, title: '울쎄라 맞고 1주일 부기 경과', hospitalName: 'FF클리닉', platform: 'INSTAGRAM', viewCount: 98000 },
      { rank: 7, title: '울쎄라 300샷 vs 600샷 차이', hospitalName: 'GG의원', platform: 'YOUTUBE', viewCount: 84000 },
      { rank: 8, title: '강남역 울쎄라 잘하는 곳 추천', hospitalName: 'HH피부과', platform: 'NAVER_BLOG', viewCount: 72000 },
      { rank: 9, title: '울쎄라 후기 6개월 변화', hospitalName: 'II클리닉', platform: 'INSTAGRAM', viewCount: 61000 },
      { rank: 10, title: '울쎄라 시술 과정 브이로그', hospitalName: 'JJ의원', platform: 'YOUTUBE', viewCount: 49000 },
    ],
    dataSource: 'mock',
  },
  필러: {
    keyword: '필러',
    monthlySearchVol: 52800,
    relatedContentCnt: 2341,
    competitorAdCnt: 51,
    avgViewCount: 9800,
    relatedKeywords: [
      { keyword: '코필러', relevanceScore: 94, monthlySearchVol: 21300 },
      { keyword: '눈밑필러', relevanceScore: 90, monthlySearchVol: 16800 },
      { keyword: '필러 가격', relevanceScore: 85, monthlySearchVol: 13200 },
      { keyword: '필러 부작용', relevanceScore: 78, monthlySearchVol: 9400 },
      { keyword: '팔자필러', relevanceScore: 70, monthlySearchVol: 7100 },
    ],
    topContents: [
      { rank: 1, title: '코필러 전후 사진 대공개', hospitalName: 'KK성형외과', platform: 'INSTAGRAM', viewCount: 428000 },
      { rank: 2, title: '눈밑 필러 후기 | 3개월 경과', hospitalName: 'LL피부과', platform: 'YOUTUBE', viewCount: 318000 },
      { rank: 3, title: '필러 가격 정리 (부위별)', hospitalName: 'MM클리닉', platform: 'NAVER_BLOG', viewCount: 241000 },
      { rank: 4, title: '팔자 필러 자연스럽게 맞는 법', hospitalName: 'NN의원', platform: 'INSTAGRAM', viewCount: 187000 },
      { rank: 5, title: '필러 녹이는 방법 | 히알루로니다제', hospitalName: 'OO피부과', platform: 'YOUTUBE', viewCount: 152000 },
      { rank: 6, title: '강남 필러 잘하는 병원 TOP5', hospitalName: 'PP클리닉', platform: 'NAVER_BLOG', viewCount: 128000 },
      { rank: 7, title: '필러 맞기 전 알아야 할 5가지', hospitalName: 'QQ의원', platform: 'YOUTUBE', viewCount: 98000 },
      { rank: 8, title: '코필러 1년 후기 (유지력 솔직 평가)', hospitalName: 'RR피부과', platform: 'INSTAGRAM', viewCount: 83000 },
      { rank: 9, title: '필러 vs 실리콘 코 | 차이점 정리', hospitalName: 'SS성형외과', platform: 'NAVER_BLOG', viewCount: 69000 },
      { rank: 10, title: '눈밑 필러 붓기 경과 (하루~1주일)', hospitalName: 'TT클리닉', platform: 'YOUTUBE', viewCount: 54000 },
    ],
    dataSource: 'mock',
  },
  슈링크: {
    keyword: '슈링크',
    monthlySearchVol: 29400,
    relatedContentCnt: 987,
    competitorAdCnt: 22,
    avgViewCount: 15600,
    relatedKeywords: [
      { keyword: '슈링크 유니버스', relevanceScore: 96, monthlySearchVol: 13200 },
      { keyword: '슈링크 가격', relevanceScore: 91, monthlySearchVol: 10800 },
      { keyword: '슈링크 효과', relevanceScore: 84, monthlySearchVol: 7400 },
      { keyword: '슈링크 vs 울쎄라', relevanceScore: 76, monthlySearchVol: 5100 },
      { keyword: '슈링크 강남 추천', relevanceScore: 67, monthlySearchVol: 3300 },
    ],
    topContents: [
      { rank: 1, title: '슈링크 유니버스 솔직 후기', hospitalName: 'UU피부과', platform: 'YOUTUBE', viewCount: 267000 },
      { rank: 2, title: '슈링크 가격 비교 총정리 2024', hospitalName: 'VV클리닉', platform: 'NAVER_BLOG', viewCount: 198000 },
      { rank: 3, title: '슈링크 1회 vs 2회 차이 비교', hospitalName: 'WW의원', platform: 'INSTAGRAM', viewCount: 154000 },
      { rank: 4, title: '슈링크 맞고 얼굴 변화 3개월', hospitalName: 'XX피부과', platform: 'YOUTUBE', viewCount: 127000 },
      { rank: 5, title: '슈링크 유니버스 출시 후기 최초 공개', hospitalName: 'YY클리닉', platform: 'INSTAGRAM', viewCount: 104000 },
      { rank: 6, title: '슈링크 고강도 vs 저강도 차이점', hospitalName: 'ZZ의원', platform: 'NAVER_BLOG', viewCount: 87000 },
      { rank: 7, title: '강남 슈링크 맛집 원장 추천', hospitalName: 'AA피부과', platform: 'YOUTUBE', viewCount: 73000 },
      { rank: 8, title: '슈링크 시술 당일 후기 브이로그', hospitalName: 'BB클리닉', platform: 'INSTAGRAM', viewCount: 61000 },
      { rank: 9, title: '슈링크 부작용 없이 맞는 법', hospitalName: 'CC의원', platform: 'NAVER_BLOG', viewCount: 49000 },
      { rank: 10, title: '40대 슈링크 6개월 변화 기록', hospitalName: 'DD피부과', platform: 'YOUTUBE', viewCount: 38000 },
    ],
    dataSource: 'mock',
  },
  리쥬란: {
    keyword: '리쥬란',
    monthlySearchVol: 22100,
    relatedContentCnt: 743,
    competitorAdCnt: 18,
    avgViewCount: 11300,
    relatedKeywords: [
      { keyword: '리쥬란힐러', relevanceScore: 98, monthlySearchVol: 9800 },
      { keyword: '리쥬란 가격', relevanceScore: 87, monthlySearchVol: 7200 },
      { keyword: '리쥬란 효과', relevanceScore: 79, monthlySearchVol: 5100 },
      { keyword: '리쥬란 아이', relevanceScore: 71, monthlySearchVol: 3700 },
      { keyword: '리쥬란 강남', relevanceScore: 63, monthlySearchVol: 2400 },
    ],
    topContents: [
      { rank: 1, title: '리쥬란힐러 1달 후기 피부변화', hospitalName: 'EE피부과', platform: 'INSTAGRAM', viewCount: 189000 },
      { rank: 2, title: '리쥬란 가격 및 효과 솔직 리뷰', hospitalName: 'FF클리닉', platform: 'YOUTUBE', viewCount: 142000 },
      { rank: 3, title: '리쥬란 vs 엑소좀 비교', hospitalName: 'GG의원', platform: 'NAVER_BLOG', viewCount: 113000 },
      { rank: 4, title: '리쥬란 아이 눈가 주름 개선 후기', hospitalName: 'HH피부과', platform: 'INSTAGRAM', viewCount: 91000 },
      { rank: 5, title: '리쥬란힐러 3회 효과 비교', hospitalName: 'II클리닉', platform: 'YOUTUBE', viewCount: 74000 },
      { rank: 6, title: '강남 리쥬란 잘하는 곳', hospitalName: 'JJ의원', platform: 'NAVER_BLOG', viewCount: 62000 },
      { rank: 7, title: '리쥬란 맞고 나서 일주일 변화', hospitalName: 'KK피부과', platform: 'INSTAGRAM', viewCount: 51000 },
      { rank: 8, title: '리쥬란힐러 붓기 얼마나 나요?', hospitalName: 'LL클리닉', platform: 'YOUTUBE', viewCount: 43000 },
      { rank: 9, title: '리쥬란 비용 절약하는 방법', hospitalName: 'MM의원', platform: 'NAVER_BLOG', viewCount: 36000 },
      { rank: 10, title: '40대 리쥬란 솔직 후기', hospitalName: 'NN피부과', platform: 'YOUTUBE', viewCount: 28000 },
    ],
    dataSource: 'mock',
  },
  바디필러: {
    keyword: '바디필러',
    monthlySearchVol: 11200,
    relatedContentCnt: 328,
    competitorAdCnt: 45,
    avgViewCount: 68000,
    relatedKeywords: [
      { keyword: '엉덩이필러', relevanceScore: 95, monthlySearchVol: 9800 },
      { keyword: '골반필러', relevanceScore: 92, monthlySearchVol: 6900 },
      { keyword: '힙업필러', relevanceScore: 88, monthlySearchVol: 5400 },
      { keyword: '바디라인', relevanceScore: 85, monthlySearchVol: 4200 },
      { keyword: '힙라인', relevanceScore: 82, monthlySearchVol: 3800 },
    ],
    topContents: [
      { rank: 1, title: '엉덩이필러 시술 전후', hospitalName: '△△의원', platform: 'INSTAGRAM', viewCount: 341000 },
      { rank: 2, title: '바디필러 후기 인터뷰', hospitalName: 'XX병원', platform: 'YOUTUBE', viewCount: 287000 },
      { rank: 3, title: '골반필러 가격 및 효과 정리', hospitalName: '○○피부과', platform: 'NAVER_BLOG', viewCount: 198000 },
      { rank: 4, title: '힙업필러 1달 변화 기록', hospitalName: '□□클리닉', platform: 'INSTAGRAM', viewCount: 156000 },
      { rank: 5, title: '바디필러 부작용 없이 맞는 법', hospitalName: '☆☆성형외과', platform: 'YOUTUBE', viewCount: 124000 },
      { rank: 6, title: '바디라인 필러 전후 비교 사진', hospitalName: '◇◇피부과', platform: 'INSTAGRAM', viewCount: 98000 },
      { rank: 7, title: '힙라인 필러 6개월 유지력 후기', hospitalName: '▽▽의원', platform: 'NAVER_BLOG', viewCount: 82000 },
      { rank: 8, title: '강남 바디필러 잘하는 곳 추천', hospitalName: '△△클리닉', platform: 'YOUTUBE', viewCount: 67000 },
      { rank: 9, title: '바디필러 시술 당일 브이로그', hospitalName: 'YY피부과', platform: 'INSTAGRAM', viewCount: 54000 },
      { rank: 10, title: '엉덩이필러 vs 지방이식 비교', hospitalName: 'ZZ의원', platform: 'YOUTUBE', viewCount: 42000 },
    ],
    dataSource: 'mock',
  },
}

export function getMockCompetitorData(keyword: string): CompetitorData {
  const data = MOCK_COMPETITOR_DATA[keyword] ?? MOCK_COMPETITOR_DATA['default']
  return { ...data, keyword }
}

export const MOCK_FUNNEL_DATA: FunnelData = {
  channels: [
    {
      name: '네이버 검색광고',
      platform: 'NAVER',
      color: '#03C75A',
      adSpend: 2400000,
      conversions: 420,
      cac: 5714,
      conversionRate: 49.41,
      roi: 2525,
      isConnected: true,
    },
    {
      name: 'Google Ads',
      platform: 'GOOGLE',
      color: '#4285F4',
      adSpend: 1900000,
      conversions: 320,
      cac: 5938,
      conversionRate: 44.44,
      roi: 2426,
      isConnected: true,
    },
    {
      name: '카카오 비즈보드',
      platform: 'KAKAO',
      color: '#FEE500',
      adSpend: 1200000,
      conversions: 240,
      cac: 5000,
      conversionRate: 41.38,
      roi: 2900,
      isConnected: true,
    },
    {
      name: '인스타그램',
      platform: 'META',
      color: '#E1306C',
      adSpend: 800000,
      conversions: 180,
      cac: 4444,
      conversionRate: 40.00,
      roi: 3275,
      isConnected: true,
    },
  ],
  totalSpend: 6300000,
  totalConversions: 1160,
  avgCac: 5431,
  overallConversionRate: 44.62,
  dataSource: 'mock',
}

export const MOCK_PROCEDURE_DATA: ProcedureData = {
  totalRevenue: 1162400000,
  totalPatients: 968,
  avgRepeatRate: 58,
  procedureTypeCount: 6,
  categoryBreakdown: [
    { name: '주사 계열', revenue: 698500000, color: '#3B82F6' },
    { name: '레이저 계열', revenue: 254900000, color: '#F59E0B' },
    { name: '리프팅 계열', revenue: 209000000, color: '#8B5CF6' },
    { name: '기타', revenue: 0, color: '#9CA3AF' },
  ],
  procedures: [
    {
      rank: 1,
      procedureName: '필러',
      category: '주사 계열',
      revenue: 248500000,
      patientCount: 207,
      repeatRate: 45,
      trendPct: 2,
      aiRecommendation: '재시술률이 낮습니다. 고객 만족도 개선 프로그램 검토를 권장합니다.',
    },
    {
      rank: 2,
      procedureName: '필러관리',
      category: '주사 계열',
      revenue: 232000000,
      patientCount: 193,
      repeatRate: 75,
      trendPct: -9,
      aiRecommendation: '시술 개선 제안이 없음. 마케팅 예산 확대 검토를 권장합니다.',
    },
    {
      rank: 3,
      procedureName: '보톡스',
      category: '주사 계열',
      revenue: 218000000,
      patientCount: 182,
      repeatRate: 43,
      trendPct: -8,
      aiRecommendation: '재시술률 주의 필요. 고객 만족도 개선 프로그램 검토를 권장합니다.',
    },
    {
      rank: 4,
      procedureName: '슈링크',
      category: '리프팅 계열',
      revenue: 145000000,
      patientCount: 121,
      repeatRate: 62,
      trendPct: 15,
      aiRecommendation: '성장세가 좋습니다. SNS 후기 콘텐츠 강화로 신환 유입을 늘리세요.',
    },
    {
      rank: 5,
      procedureName: '리쥬란',
      category: '주사 계열',
      revenue: 134000000,
      patientCount: 112,
      repeatRate: 71,
      trendPct: 7,
      aiRecommendation: '재시술률이 우수합니다. 패키지 프로그램 도입으로 매출 극대화를 권장합니다.',
    },
    {
      rank: 6,
      procedureName: '레이저토닝',
      category: '레이저 계열',
      revenue: 124900000,
      patientCount: 153,
      repeatRate: 68,
      trendPct: 3,
      aiRecommendation: '안정적인 성과입니다. 계절 이벤트 연계 프로모션을 검토하세요.',
    },
  ],
  dataSource: 'mock',
}
